package main

// viewerHTML deliberately has no external assets: it is the full local UI.
const viewerHTML = `<!doctype html>
<html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Agent Trace Viewer</title>
<style>
*{box-sizing:border-box}body{margin:0;background:#10131a;color:#e8ecf2;font:14px system-ui,sans-serif}header{padding:18px 24px;border-bottom:1px solid #303846}h1{font-size:20px;margin:0}#layout{display:grid;grid-template-columns:minmax(420px,1fr) 360px;min-height:calc(100vh - 60px)}main{padding:20px 24px}.row{display:grid;grid-template-columns:1.25fr .6fr .3fr 1.5fr;gap:10px;align-items:center;padding:8px;border-radius:5px;cursor:pointer}.row:hover,.row.active{background:#202735}.tree .row{margin-left:calc(var(--depth) * 20px)}.name{font-weight:600}.meta{color:#aeb8c8;font-variant-numeric:tabular-nums}.bar{height:8px;background:#34445c;border-radius:8px;overflow:hidden}.bar i{display:block;height:100%;background:#60a5fa;border-radius:8px}.error .bar i{background:#fb7185}.error .status{color:#fb7185}.ok .status{color:#6ee7b7}aside{padding:20px;border-left:1px solid #303846;background:#151a23}pre{white-space:pre-wrap;overflow-wrap:anywhere;background:#0c0f15;padding:12px;border-radius:6px;color:#c8d4e5}button{border:0;background:transparent;color:#aeb8c8;cursor:pointer;font-size:12px}.child.hidden{display:none}.empty{color:#aeb8c8}@media(max-width:850px){#layout{grid-template-columns:1fr}aside{border-left:0;border-top:1px solid #303846}}
</style>
<header><h1 id="title">Agent Trace Viewer</h1></header><div id="layout"><main><div class="row meta"><span>SPAN</span><span>DURATION</span><span>STATUS</span><span>TIMELINE</span></div><div id="tree"></div></main><aside><h2>Span details</h2><div id="details" class="empty">Select a span to inspect its attributes or error.</div></aside></div>
<script>
const fmt=d=>d<1?Math.round(d*1000)+'µs':d<1000?d.toFixed(1)+'ms':(d/1000).toFixed(2)+'s';
fetch('/api/trace').then(r=>r.json()).then(trace=>{const spans=trace.spans||[],byId=new Map(spans.map(s=>[s.span_id,{...s,children:[]}])),roots=[];for(const s of byId.values()){const p=byId.get(s.parent_span_id);if(s.parent_span_id&&p&&p!==s)p.children.push(s);else{if(s.parent_span_id)s.orphan=true;roots.push(s)}}const start=Date.parse(trace.started_at),total=Math.max(1,Date.parse(trace.ended_at)-start);document.querySelector('#title').textContent='Agent Trace Viewer · '+trace.trace_id;const tree=document.querySelector('#tree');function draw(nodes,depth,host){nodes.sort((a,b)=>Date.parse(a.started_at)-Date.parse(b.started_at));for(const s of nodes){const wrap=document.createElement('div'),row=document.createElement('div'),duration=Date.parse(s.ended_at)-Date.parse(s.started_at);wrap.className='node '+s.status;row.className='row';row.style.setProperty('--depth',depth);const toggle=s.children.length?'<button>▾</button>':'<span></span>';row.innerHTML=toggle+'<span class="name">'+(s.orphan?'[ORPHAN] ':'')+escapeHTML(s.name)+' <small>['+s.kind+']</small></span><span class="meta">'+fmt(duration)+'</span><span class="status">'+s.status+'</span><span class="bar"><i style="margin-left:'+((Date.parse(s.started_at)-start)/total*100)+'%;width:'+Math.max(1,duration/total*100)+'%"></i></span>';row.onclick=e=>{if(e.target.tagName==='BUTTON'){const c=wrap.querySelector('.child');if(c){c.classList.toggle('hidden');e.target.textContent=c.classList.contains('hidden')?'▸':'▾'}e.stopPropagation();return}document.querySelectorAll('.row.active').forEach(x=>x.classList.remove('active'));row.classList.add('active');document.querySelector('#details').className='';document.querySelector('#details').innerHTML='<strong>'+escapeHTML(s.name)+'</strong><pre>'+escapeHTML(JSON.stringify({attributes:s.attributes||{},error:s.error||null,tokens:s.tokens||null,cost_usd:s.cost_usd||0},null,2))+'</pre>'};wrap.appendChild(row);if(s.children.length){const c=document.createElement('div');c.className='child';draw(s.children,depth+1,c);wrap.appendChild(c)}host.appendChild(wrap)}}draw(roots,0,tree)}).catch(e=>document.querySelector('#details').textContent='Could not load trace: '+e);function escapeHTML(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
</script></html>`
